apiVersion: tekton.dev/v1alpha1
kind: ClusterTask
metadata:
  name: steward-jenkinsfile-runner
  labels:
    {{- include "steward.labels" . | nindent 4 }}
    {{- include "steward.runController.componentLabel" . | nindent 4 }}
spec:
  inputs:
    params:
    - name: PIPELINE_PARAMS_JSON
      type: string
      description: >
        Parameters to pass to the pipeline, as JSON string.
    - name: PIPELINE_GIT_URL
      type: string
      description: >
        The URL of the Git repository containing the pipeline definition.
    - name: PIPELINE_GIT_REVISION
      type: string
      description: >
        The revision of the pipeline Git repository to used, e.g. 'master'.
    - name: PIPELINE_FILE
      type: string
      description: >
        The relative pathname of the pipeline definition file, typically 'Jenkinsfile'.
    - name: PIPELINE_LOG_ELASTICSEARCH_INDEX_URL
      type: string
      description: >
        The URL of the Elasticsearch index to send logs to.
        If null or empty, logging to Elasticsearch is disabled.
        # Example: http://elasticsearch-master.elasticsearch.svc.cluster.local:9200/jenkins-logs/_doc
      default: {{ default "" .Values.pipelineRuns.logging.elasticsearch.indexURL | quote }}
    - name: PIPELINE_LOG_ELASTICSEARCH_AUTH_SECRET
      type: string
      description: >
        The name of the secret of type basic-auth to use to authenticate to Elasticsearch.
        If null or empty, no authentication takes place.
      default: ""
    - name: PIPELINE_LOG_ELASTICSEARCH_TRUSTEDCERTS_SECRET
      type: string
      description: >
        The name of the secret providing the trusted certificates bundle used for TLS server verification when connecting to Elasticsearch.
        If null or empty, the default trusted certificates are used.
      default: ""
    - name: PIPELINE_LOG_ELASTICSEARCH_RUN_ID_JSON
      type: string
      description: >
        The value for the 'runId' field of log events, as JSON string.
        Must be specified if logging to Elasticsearch is enabled.
      default: ""
    - name: RUN_NAMESPACE
      type: string
      description: >
        The namespace of this pipeline run.
    - name: JOB_NAME
      type: string
      description: >
        The name of the job this pipeline run belongs to. It is used as the name of the Jenkins job and therefore must be a valid Jenkins job name.
        If null or empty, `job` will be used.
      default: ""
    - name: RUN_NUMBER
      type: string
      description: >
        The sequence number of the pipeline run, which translates into the build number of the Jenkins job.
        If null or empty, `1` is used.
      default: "1"
    - name: RUN_CAUSE
      type: string
      description: >
        A textual description of the cause of this pipeline run. Will be set as cause of the Jenkins job.
        If null or empty, no cause information will be available.
      default: ""
  steps:
  - name: jenkinsfile-runner
    {{- with .Values.pipelineRuns.jenkinsfileRunner.image }}
    image: {{ printf "%s:%s" .repository .tag | quote }}
    imagePullPolicy: {{ .pullPolicy | quote }}
    {{- end }}
    args: []
    env:
    - name: XDG_CONFIG_HOME
      value: /home/jenkins
    - name: JAVA_OPTS
      value: '-Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.8'
    - name: PIPELINE_GIT_URL
      value: '$(inputs.params.PIPELINE_GIT_URL)'
    - name: PIPELINE_GIT_REVISION
      value: '$(inputs.params.PIPELINE_GIT_REVISION)'
    - name: PIPELINE_FILE
      value: '$(inputs.params.PIPELINE_FILE)'
    - name: PIPELINE_PARAMS_JSON
      value: '$(inputs.params.PIPELINE_PARAMS_JSON)'
    - name: PIPELINE_LOG_ELASTICSEARCH_INDEX_URL
      value: '$(inputs.params.PIPELINE_LOG_ELASTICSEARCH_INDEX_URL)'
    - name: PIPELINE_LOG_ELASTICSEARCH_AUTH_SECRET
      value: '$(inputs.params.PIPELINE_LOG_ELASTICSEARCH_AUTH_SECRET)'
    - name: PIPELINE_LOG_ELASTICSEARCH_TRUSTEDCERTS_SECRET
      value: '$(inputs.params.PIPELINE_LOG_ELASTICSEARCH_TRUSTEDCERTS_SECRET)'
    - name: PIPELINE_LOG_ELASTICSEARCH_RUN_ID_JSON
      value: '$(inputs.params.PIPELINE_LOG_ELASTICSEARCH_RUN_ID_JSON)'
    - name: RUN_NAMESPACE
      value: '$(inputs.params.RUN_NAMESPACE)'
    - name: JOB_NAME
      value: '$(inputs.params.JOB_NAME)'
    - name: RUN_NUMBER
      value: '$(inputs.params.RUN_NUMBER)'
    - name: RUN_CAUSE
      value: '$(inputs.params.RUN_CAUSE)'
    resources:
      {{- toYaml .Values.pipelineRuns.jenkinsfileRunner.resources | nindent 6 }}
    {{- if .Values.pipelineRuns.jenkinsfileRunner.terminationMessagePath }}
    terminationMessagePath: {{ .Values.pipelineRuns.jenkinsfileRunner.terminationMessagePath | quote }}
    {{- end }}
