apiVersion: apps/v1
kind: Deployment
metadata:
  name: steward-tenant-controller
  namespace: {{ .Values.targetNamespace.name | quote }}
  labels:
    {{- include "steward.labels" . | nindent 4 }}
    {{- include "steward.tenantController.componentLabel" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "steward.selectorLabels" . | nindent 6 }}
      {{- include "steward.tenantController.componentLabel" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "steward.selectorLabels" . | nindent 8 }}
        {{- include "steward.tenantController.componentLabel" . | nindent 8 }}
    spec:
      serviceAccountName: steward-tenant-controller
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.tenantController.podSecurityContext | nindent 8 }}
      containers:
      - name: controller
        securityContext:
          {{- toYaml .Values.tenantController.securityContext | nindent 10 }}
        {{- with .Values.tenantController.image }}
        image: {{ printf "%s:%s" .repository .tag | quote }}
        imagePullPolicy: {{ .pullPolicy | quote }}
        {{- end }}
        args:
        - {{ printf "-qps=%d" ( .Values.tenantController.args.qps | int ) | quote }}
        - {{ printf "-burst=%d" ( .Values.tenantController.args.burst | int ) | quote }}
        - {{ printf "-threadiness=%d" ( .Values.tenantController.args.threadiness | int ) | quote }}
        {{- if .Values.tenantController.args.logVerbosity }}
        - {{ printf "-v=%d" ( .Values.tenantController.args.logVerbosity | int ) | quote }}
        {{- end }}
        command:
        - /app/steward-tenantctl
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: STEWARD_FEATURE_FLAGS
          value: {{ .Values.featureFlags | quote }}
        ports:
          - name: http-metrics
            containerPort: 9090
            protocol: TCP
        resources:
          {{- toYaml .Values.tenantController.resources | nindent 10 }}
      {{- with .Values.tenantController.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tenantController.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tenantController.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
