apiVersion: apps/v1
kind: Deployment
metadata:
  name: steward-tenant-controller
  namespace: steward-system
  labels:
    app: steward-tenant-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steward-tenant-controller
  template:
    metadata:
      labels:
        app: steward-tenant-controller
    spec:
      serviceAccountName: steward-system
      containers:
      - name: steward-tenant-controller
        image: stewardci/stewardci-tenant-controller:200122_02decab
        imagePullPolicy: IfNotPresent
        ports:
          - name: http-metrics
            containerPort: 9090
            protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 32Mi
          requests:
            cpu: 10m
