apiVersion: apps/v1
kind: Deployment
metadata:
  name: steward-run-controller
  namespace: steward-system
  labels:
    app: steward-run-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steward-run-controller
  template:
    metadata:
      labels:
        app: steward-run-controller
    spec:
      serviceAccountName: steward-system
      containers:
      - name: steward-run-controller
        imagePullPolicy: IfNotPresent
        image: stewardci/stewardci-run-controller:191205_ab043b3
